name: vzc-project

dependencies:
  - python=3.7
  - pandas=1.1.3
  - numpy=1.19.1
  - seaborn=0.11.0
  - ipython=7.12
  - jupyter=1.0
  - matplotlib=3.1
  - scikit-learn=0.23.2
  - scipy=1.4
  - spyder=4.1.5

